# Czas w sekundach na wybór systemu z menu (0 oznacza natychmiastowy start)
timeout: 3

# Nazwa Twojego systemu wyświetlana w menu startowym
/Nexus (x86_64)
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    # Wymuszamy nowoczesne, ostre Full HD (lub zmień na 1280x720 jeśli Twój monitor jest mniejszy)
    interface_resolution: 1024x768
    module_path: boot():/boot/initramfs.tar
